export const MODE_SELECT = "MODE_SELECT";
export const MODE_DRAG = "MODE_DRAG";
export const MODE_CREATE_PATH_ELEMENT = "MODE_CREATE_PATH_ELEMENT";
export const MODE_CREATE_NODE_ELEMENT = "MODE_CREATE_NODE_ELEMENT";
export const MODE_RECTANGLE_SELECTION = "MODE_RECTANGLE_SELECTION";

// for dragging the all svg
export const MODE_MOVE_PAPER = "MODE_MOVE_PAPER";
